name: Run download-station-data.py and commit new files

permissions:
    contents: write
    pull-requests: read

on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    download:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11" # Specify the exact Python version if required

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run download-station-data.py
              run: python download-station-data.py
              continue-on-error: false

            - name: Check for changes
              id: changes
              run: |
                  git add station_status/*
                  if git diff --quiet; then
                    echo "::set-output name=changed::false"
                  else
                    echo "::set-output name=changed::true"
                  fi

            - name: Commit and push if it changed
              if: steps.changes.outputs.changed == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m "Update station data"
                  git push
